project:
  type: website
  output-dir: docs

website:
  title: "my personal website"
  favicon: favicon.png
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: movies.qmd
        text: Movie
      - href: FYP_project.qmd
        text: FYP Project
      - href: Reflection_on_the_use_of_GenAI.qmd
        text: Reflection on the use of GenAI

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc-depth: 3
    toc-location: left
    




